# 仅替换发生崩溃的 Windows 插件源文件，其他上游源码保持不变。
if(NOT TARGET flutter_inappwebview_windows_plugin)
  message(FATAL_ERROR "flutter_inappwebview_windows 插件目标不存在")
endif()
target_compile_options(
  flutter_inappwebview_windows_plugin
  PRIVATE /wd4458)

set(FLUTTER_INAPPWEBVIEW_WINDOWS_ROOT
  "${CMAKE_CURRENT_SOURCE_DIR}/flutter/ephemeral/.plugin_symlinks/flutter_inappwebview_windows/windows")
set(FLUTTER_INAPPWEBVIEW_WINDOWS_ORIGINAL_SOURCE
  "${FLUTTER_INAPPWEBVIEW_WINDOWS_ROOT}/webview_environment/webview_environment.cpp")
set(FLUTTER_INAPPWEBVIEW_WINDOWS_PATCHED_SOURCE
  "${CMAKE_CURRENT_BINARY_DIR}/patched_plugins/flutter_inappwebview_windows/webview_environment.cpp")

execute_process(
  COMMAND "${CMAKE_COMMAND}"
    "-DINPUT_FILE=${FLUTTER_INAPPWEBVIEW_WINDOWS_ORIGINAL_SOURCE}"
    "-DOUTPUT_FILE=${FLUTTER_INAPPWEBVIEW_WINDOWS_PATCHED_SOURCE}"
    -P "${CMAKE_CURRENT_LIST_DIR}/patch_flutter_inappwebview_windows.cmake"
  RESULT_VARIABLE FLUTTER_INAPPWEBVIEW_WINDOWS_PATCH_RESULT
  OUTPUT_VARIABLE FLUTTER_INAPPWEBVIEW_WINDOWS_PATCH_OUTPUT
  ERROR_VARIABLE FLUTTER_INAPPWEBVIEW_WINDOWS_PATCH_ERROR)
if(NOT FLUTTER_INAPPWEBVIEW_WINDOWS_PATCH_RESULT EQUAL 0)
  message(FATAL_ERROR
    "应用 flutter_inappwebview_windows 生命周期补丁失败:\n"
    "${FLUTTER_INAPPWEBVIEW_WINDOWS_PATCH_OUTPUT}"
    "${FLUTTER_INAPPWEBVIEW_WINDOWS_PATCH_ERROR}")
endif()

get_target_property(
  FLUTTER_INAPPWEBVIEW_WINDOWS_SOURCES
  flutter_inappwebview_windows_plugin
  SOURCES)
if(FLUTTER_INAPPWEBVIEW_WINDOWS_SOURCES MATCHES "-NOTFOUND$")
  message(FATAL_ERROR
    "WEBVIEW_PATCH_SOURCE_COUNT: 未读取到插件目标源文件")
endif()
set(FLUTTER_INAPPWEBVIEW_WINDOWS_PATCHED_SOURCES)
set(FLUTTER_INAPPWEBVIEW_WINDOWS_ORIGINAL_SOURCE_COUNT 0)
set(FLUTTER_INAPPWEBVIEW_WINDOWS_EXISTING_PATCH_COUNT 0)
foreach(SOURCE_FILE IN LISTS FLUTTER_INAPPWEBVIEW_WINDOWS_SOURCES)
  if(SOURCE_FILE MATCHES "^\\$<")
    list(APPEND FLUTTER_INAPPWEBVIEW_WINDOWS_PATCHED_SOURCES "${SOURCE_FILE}")
    continue()
  endif()
  get_filename_component(
    SOURCE_FILE_ABSOLUTE
    "${SOURCE_FILE}"
    ABSOLUTE
    BASE_DIR "${FLUTTER_INAPPWEBVIEW_WINDOWS_ROOT}")
  if("${SOURCE_FILE_ABSOLUTE}" STREQUAL
      "${FLUTTER_INAPPWEBVIEW_WINDOWS_ORIGINAL_SOURCE}")
    math(EXPR FLUTTER_INAPPWEBVIEW_WINDOWS_ORIGINAL_SOURCE_COUNT
      "${FLUTTER_INAPPWEBVIEW_WINDOWS_ORIGINAL_SOURCE_COUNT} + 1")
    continue()
  endif()
  if("${SOURCE_FILE_ABSOLUTE}" STREQUAL
      "${FLUTTER_INAPPWEBVIEW_WINDOWS_PATCHED_SOURCE}")
    math(EXPR FLUTTER_INAPPWEBVIEW_WINDOWS_EXISTING_PATCH_COUNT
      "${FLUTTER_INAPPWEBVIEW_WINDOWS_EXISTING_PATCH_COUNT} + 1")
  endif()
  list(APPEND
    FLUTTER_INAPPWEBVIEW_WINDOWS_PATCHED_SOURCES
    "${SOURCE_FILE_ABSOLUTE}")
endforeach()
if(NOT FLUTTER_INAPPWEBVIEW_WINDOWS_ORIGINAL_SOURCE_COUNT EQUAL 1)
  message(FATAL_ERROR
    "WEBVIEW_PATCH_SOURCE_COUNT: 原始环境源文件必须恰好注册一次，实际 ${FLUTTER_INAPPWEBVIEW_WINDOWS_ORIGINAL_SOURCE_COUNT} 次")
endif()
if(NOT FLUTTER_INAPPWEBVIEW_WINDOWS_EXISTING_PATCH_COUNT EQUAL 0)
  message(FATAL_ERROR
    "WEBVIEW_PATCH_SOURCE_COUNT: 补丁环境源文件在替换前不应注册")
endif()
list(APPEND
  FLUTTER_INAPPWEBVIEW_WINDOWS_PATCHED_SOURCES
  "${FLUTTER_INAPPWEBVIEW_WINDOWS_PATCHED_SOURCE}")
set_property(
  TARGET flutter_inappwebview_windows_plugin
  PROPERTY SOURCES "${FLUTTER_INAPPWEBVIEW_WINDOWS_PATCHED_SOURCES}")

get_target_property(
  FLUTTER_INAPPWEBVIEW_WINDOWS_VERIFIED_SOURCES
  flutter_inappwebview_windows_plugin
  SOURCES)
set(FLUTTER_INAPPWEBVIEW_WINDOWS_REMAINING_ORIGINAL_COUNT 0)
set(FLUTTER_INAPPWEBVIEW_WINDOWS_FINAL_PATCH_COUNT 0)
foreach(SOURCE_FILE IN LISTS FLUTTER_INAPPWEBVIEW_WINDOWS_VERIFIED_SOURCES)
  if(SOURCE_FILE MATCHES "^\\$<")
    continue()
  endif()
  get_filename_component(
    SOURCE_FILE_ABSOLUTE
    "${SOURCE_FILE}"
    ABSOLUTE
    BASE_DIR "${FLUTTER_INAPPWEBVIEW_WINDOWS_ROOT}")
  if("${SOURCE_FILE_ABSOLUTE}" STREQUAL
      "${FLUTTER_INAPPWEBVIEW_WINDOWS_ORIGINAL_SOURCE}")
    math(EXPR FLUTTER_INAPPWEBVIEW_WINDOWS_REMAINING_ORIGINAL_COUNT
      "${FLUTTER_INAPPWEBVIEW_WINDOWS_REMAINING_ORIGINAL_COUNT} + 1")
  endif()
  if("${SOURCE_FILE_ABSOLUTE}" STREQUAL
      "${FLUTTER_INAPPWEBVIEW_WINDOWS_PATCHED_SOURCE}")
    math(EXPR FLUTTER_INAPPWEBVIEW_WINDOWS_FINAL_PATCH_COUNT
      "${FLUTTER_INAPPWEBVIEW_WINDOWS_FINAL_PATCH_COUNT} + 1")
  endif()
endforeach()
if(NOT FLUTTER_INAPPWEBVIEW_WINDOWS_REMAINING_ORIGINAL_COUNT EQUAL 0 OR
    NOT FLUTTER_INAPPWEBVIEW_WINDOWS_FINAL_PATCH_COUNT EQUAL 1)
  message(FATAL_ERROR
    "WEBVIEW_PATCH_SOURCE_COUNT: 插件环境源文件替换结果无效")
endif()
target_include_directories(
  flutter_inappwebview_windows_plugin
  PRIVATE "${FLUTTER_INAPPWEBVIEW_WINDOWS_ROOT}/webview_environment")

message(STATUS "已应用 flutter_inappwebview_windows 环境生命周期补丁")
