set(KANYINGYIN_LIBMPV_BUNDLE_ID "20260730-ad59ff1b4-ffmpeg8.1.2-r2")
set(KANYINGYIN_LIBMPV_SHA256
  "6CC4EAA6E60128A4C61E7F1BF6FE79FD4BC40A2A4DDF9CBDEB3363C520599BBF")

if(DEFINED ENV{KANYINGYIN_WINDOWS_LIBMPV_ROOT}
    AND NOT "$ENV{KANYINGYIN_WINDOWS_LIBMPV_ROOT}" STREQUAL "")
  file(TO_CMAKE_PATH "$ENV{KANYINGYIN_WINDOWS_LIBMPV_ROOT}" FULL_LIBMPV_DIR)
elseif(DEFINED ENV{USERPROFILE} AND NOT "$ENV{USERPROFILE}" STREQUAL "")
  file(TO_CMAKE_PATH
    "$ENV{USERPROFILE}/.kanyingyin/windows/libmpv/${KANYINGYIN_LIBMPV_BUNDLE_ID}"
    FULL_LIBMPV_DIR)
else()
  message(FATAL_ERROR
    "无法定位看影音 Windows 播放器组件：缺少 USERPROFILE，"
    "也未设置 KANYINGYIN_WINDOWS_LIBMPV_ROOT")
endif()

set(FULL_LIBMPV_MANIFEST
  "${FULL_LIBMPV_DIR}/kanyingyin-libmpv-manifest.json")
set(FULL_LIBMPV_DLL "${FULL_LIBMPV_DIR}/libmpv-2.dll")
set(FULL_LIBMPV_REQUIRED_FILES
  "${FULL_LIBMPV_MANIFEST}"
  "${FULL_LIBMPV_DLL}"
  "${FULL_LIBMPV_DIR}/avcodec-62.dll"
  "${FULL_LIBMPV_DIR}/avformat-62.dll"
  "${FULL_LIBMPV_DIR}/avutil-60.dll"
  "${FULL_LIBMPV_DIR}/swresample-6.dll"
  "${FULL_LIBMPV_DIR}/swscale-9.dll")

foreach(REQUIRED_FILE IN LISTS FULL_LIBMPV_REQUIRED_FILES)
  if(NOT EXISTS "${REQUIRED_FILE}")
    message(FATAL_ERROR
      "缺少看影音已验证 Windows 播放器组件：${REQUIRED_FILE}\n"
      "请先运行 tool/windows/prepare_compatible_libmpv.ps1。")
  endif()
endforeach()

file(SHA256 "${FULL_LIBMPV_DLL}" FULL_LIBMPV_ACTUAL_SHA256)
string(TOUPPER "${FULL_LIBMPV_ACTUAL_SHA256}" FULL_LIBMPV_ACTUAL_SHA256)
if(NOT FULL_LIBMPV_ACTUAL_SHA256 STREQUAL KANYINGYIN_LIBMPV_SHA256)
  message(FATAL_ERROR
    "看影音 Windows 播放器组件哈希不匹配，拒绝回退到未经联合验证的 libmpv。")
endif()

file(READ "${FULL_LIBMPV_MANIFEST}" FULL_LIBMPV_MANIFEST_CONTENT)
string(JSON FULL_LIBMPV_MANIFEST_BUNDLE_ID GET
  "${FULL_LIBMPV_MANIFEST_CONTENT}" bundleId)
if(NOT FULL_LIBMPV_MANIFEST_BUNDLE_ID STREQUAL KANYINGYIN_LIBMPV_BUNDLE_ID)
  message(FATAL_ERROR "看影音 Windows 播放器组件清单标识无效。")
endif()

file(GLOB FULL_LIBMPV_RUNTIME_DLLS CONFIGURE_DEPENDS
  "${FULL_LIBMPV_DIR}/*.dll")
set(FULL_LIBMPV_FORBIDDEN_DLLS
  "dartjni.dll"
  "flutter_windows.dll"
  "WebView2Loader.dll")
foreach(RUNTIME_DLL IN LISTS FULL_LIBMPV_RUNTIME_DLLS)
  get_filename_component(RUNTIME_DLL_NAME "${RUNTIME_DLL}" NAME)
  if(RUNTIME_DLL_NAME MATCHES "_plugin\\.dll$"
      OR RUNTIME_DLL_NAME IN_LIST FULL_LIBMPV_FORBIDDEN_DLLS)
    message(FATAL_ERROR
      "看影音播放器组件不得覆盖应用或 Flutter 运行库：${RUNTIME_DLL_NAME}")
  endif()
endforeach()
list(LENGTH FULL_LIBMPV_RUNTIME_DLLS FULL_LIBMPV_RUNTIME_DLL_COUNT)
if(FULL_LIBMPV_RUNTIME_DLL_COUNT LESS 6)
  message(FATAL_ERROR "看影音 Windows 播放器组件运行库不完整。")
endif()
